apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dynamic-pvc
  annotations:
    nodename: 172.31.15.152
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi